site_name: strohb
repo_url: https://github.com/brianjstroh/strohb/
site_url: https://www.strohb.com
edit_uri: https://github.com/brianjstroh/strohb/docs/
site_description: A playground for data engineers
site_author: Brian Stroh
nav:
  - Home: index.md
  - Blog:
    - January 17, 2024: blog/2024/1/17.md
    - January 25, 2024: blog/2024/1/25.md
    - January 31, 2024: blog/2024/1/31.md
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: green
